# Generated by Django 6.1.1 on 2026-09-27 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_summary', models.CharField(max_length=255)),
                ('task_detail', models.TextField()),
                ('task_deadline', models.DateTimeField()),
                ('task_status', models.CharField(choices=[('Pending', 'Pending'), ('completed', 'Completed'), ('incomplete', 'Incomplete')], default='Pending')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
